<!doctype html>
<html>
	<head>
		<script type="text/javascript">
			window.print();
		</script>
		<link rel="stylesheet" media="print" href="<?php echo $this->baseUrl('/resources/css/print.css');?>" type="text/css" />
		<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/resources/css/print.css');?>" type="text/css" />
		<script type="text/javascript" src="<?php echo $this->baseUrl('/resources/js/ext-all.js');?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('/resources/js/jquery.min.js');?>"></script>
		<title><?php echo $this->details['COMPANY_NAME'] ?></title>
	</head>
	<body>
		<div id="content">
			<div id="header">
				<center><h2><?php echo $this->details['COMPANY_NAME']?></h2></center>
			</div>
			<div id="detail">
				<div id="dkiri">
					<div id="head">
					<h3>Detail</h3>
					</div>
					<div id="alignki">
						<div id="title1"> Equity Asset(MM): </div> 
							<div id="isi"><?php echo $this->details['EQUITY_ASSETS']?></div>
						<div id="title1"> Investor Type : </div> 
							<div id="isi"><?php echo $this->details['INVESTOR_TYPE']?></div>
						<div id="title1"> Style : </div> 
							<div id="isi"><?php echo $this->details['STYLE'] ?></div>
						<div id="title1"> Latest Update :  </div> 
							<div id="isi"><?php echo $this->details['MODIFIED_DATE'] ?></div>		
					</div>					
				</div>
				<div id="dkanan">
					<div id="head">
					<h3>Company Address</h3>
					</div>
					
					<div id="alignka">
						<div id="address">
							<?php echo $this->details['ADDRESS']?><br>
							<?php echo $this->details['LOCATION']?>
						</div>
						<div id="phone">
							Phone : <?php echo $this->details['PHONE_1'] ?><br/>
							Fax : <?php echo $this->details['FAX'] ?><br>
							Website: <?php echo $this->details['WEBSITE'] ?>
						</div> 
					</div>					
				</div>	
			</div>
			<div id="detail2">
				<div id="head2">
					<h3>Company Overview</h3>
				</div>
				<?php echo $this->details['COMPANY_OVERVIEW'];?>
			</div>
			<div id="detail2">
				<div id="head2">
					<h3>Invesment Strategy</h3>
				</div>
				<?php echo $this->details['INVESTMENT_STRATEGY'];?>
			</div>
			
				<div id="detail3">
					<div id="headSec">
						<h3>Sector Holdings</h3>
					</div>
					<div id="headPor">
						<h3>Portfolio Distribution</h3>
					</div>
				</div>	
					<script type="text/javascript">
					 	/*
						 * Sector Holdings
						 */
						
						Ext.define("SectorHolding", { extend: "Ext.data.Model", fields: [{"name":"SECTOR_HOLDING_ID","type":"int"},{"name":"INVESTOR_ID","type":"int"},{"name":"TITLE","type":"string"},{"name":"VALUE","type":"float"},{"name":"CREATED_DATE","type":"string"},{"name":"MODIFIED_DATE","type":"string"}] });
						var storeSE = Ext.create('Ext.data.Store', {
							model: 'SectorHolding',
							storeId: 'SectorHoldings',
							proxy: {
								extraParams:{
									id:<?php echo $this->details['INVESTOR_ID'];?>
								},
						        type: "ajax",
						        api: {
						            "read": "\/sectorholdings\/request\/read",
						            "create": "\/sectorholdings\/request\/create",
						            "update": "\/sectorholdings\/request\/update",
						            "destroy": "\/sectorholdings\/request\/destroy"
						        },
						        actionMethods: {
						            "create": "POST",
						            "destroy": "POST",
						            "read": "POST",
						            "update": "POST"
						        },
						        reader: {
						            "idProperty": "TITLE",
						            "type": "json",
						            "root": "data.items",
						            "totalProperty": "data.totalCount"
						        },
						        writer: {
						            "type": "json",
						            "root": "data",
						            "writeAllFields": true
						        }
						    },
						    sorter: {
						        "property": "TITLE",
						        "direction": "ASC"
						    }
						});
						storeSE.load();
					
						/*
						 * End of : Sector Holdings
						 */
					
    					var panel1 = Ext.create('widget.panel',{					   
					    renderTo: Ext.getBody(),
					    width: 420,
						height: 250,
						style: {
							float: 'left',
							width: '50%'
						},
					    layout: 'fit',
					    items: [{
								xtype: 'chart',
								store: storeSE,
								id:'chartCmp',
								animate: true,
								legend: {
									position: 'right'
								},
								series: [{
									type: 'pie',
									field: 'VALUE',
									showInLegend: true,
									highlight: {
										segment: {
											margin: 20
										}
									},
									label: {
										field: 'TITLE',
										contrast: true,
										display: 'none',
										font: '12px Arial'
									}
								}]
							}]
							
					   });
					
					</script>
										
					<script type="text/javascript">
					/*
					 * Portfolio Distributions
					 */
					Ext.define("PortfolioDistribution", { extend: "Ext.data.Model", fields: [{"name":"PORTFOLIO_DISTRIBUTION_ID","type":"int"},{"name":"PORTFOLIO_DISTRIBUTION_ID","type":"int"},{"name":"INVESTOR_ID","type":"int"},{"name":"TITLE","type":"string"},{"name":"VALUE","type":"float"},{"name":"CREATED_DATE","type":"string"},{"name":"MODIFIED_DATE","type":"string"}] });
					var storePD = Ext.create('Ext.data.Store', {
						model: 'PortfolioDistribution',
						storeId: 'PortfolioDistributions',
						proxy: {
							extraParams:{id:<?php echo $this->details['INVESTOR_ID']; ?>},
					        "type": "ajax",
					        "api": {
					            "read": "\/portfoliodistribution\/request\/read",
					            "create": "\/portfoliodistribution\/request\/create",
					            "update": "\/portfoliodistribution\/request\/update",
					            "destroy": "\/portfoliodistribution\/request\/destroy"
					        },
					        "actionMethods": {
					            "create": "POST",
					            "destroy": "POST",
					            "read": "POST",
					            "update": "POST"
					        },
					        "reader": {
					            "idProperty": "TITLE",
					            "type": "json",
					            "root": "data.items",
					            "totalProperty": "data.totalCount"
					        },
					        "writer": {
					            "type": "json",
					            "root": "data",
					            "writeAllFields": true
					        }
					    },
					    sorter: {
					        "property": "TITLE",
					        "direction": "ASC"
					    },
					});
					
					storePD.load();
					
					var panel2 = Ext.create('widget.panel',{					   
					    renderTo: Ext.getBody(),
					    width: 420,
					    style: {
							float: 'right',
							width: '50%'
						},
						height: 250,
					    layout: 'fit',
					    items: [{
							xtype: 'chart',
							animate: {
								easing: 'bounceOut',
								duration: 400
							},
							store: storePD,
							shadow: true,
							width: 580,
							height: 300,
							style: 'background: #FFF',
							theme: 'Base:gradients',
							axes: [{
								type: 'Numeric',
								position: 'left',
								fields: ['VALUE'],
								label: {
									renderer: Ext.util.Format.numberRenderer('0,0')
								},
								grid: true,
								minimum: 0
							},{
								type: 'Category',
								position: 'bottom',
								fields: ['TITLE'],
							}],
							series: [{
								type: 'column',
								axis: 'left',
								highlight: true,
								label: {
									display: 'insideEnd',
					                  'text-anchor': 'middle',
					                   field: 'VALUE',
					                   orientation: 'horizontal',
					                   fill: '#FFF',
					                   font: '14px Arial'
								},
								xField: 'TITLE',
					            yField: 'VALUE'
							}]
						}]
					
					   });
					</script>
		</div>
	</body>
</html>