<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle() . "\n"?>
		
		<!-- Start : CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/ext-all.css')?>" type="text/css" />
		<!-- End of : CSS -->
		<!-- Start : JS -->
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/ext-all.js')?>"></script>
		<script type="text/javascript">
			Ext.define('sharedData', {
				singleton: true,
				baseUrl: '<?php echo $this->baseUrl()?>'
			});
		</script>
		<!-- End of : JS -->
	</head>
	<body>
	<?php echo $this->layout()->content . "\n"?>
	</body>
</html>