CREATE TABLE SHAREHOLDING_AMOUNTS(
 SHAREHOLDING_AMOUNT_ID INT(19) NOT NULL PRIMARY KEY AUTO_INCREMENT,
 SHAREHOLDING_ID INT(19) NOT NULL,
 AMOUNT FLOAT DEFAULT 0 NOT NULL,
 CREATED_DATE DATETIME NOT NULL,
 MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(SHAREHOLDING_ID) REFERENCES SHAREHOLDINGS(SHAREHOLDING_ID) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE=InnoDB;
